/*
 *  net_rig.c -- four peers, one process, the REAL netchannel.c.
 *
 *  Each peer is engine/src/netchannel.c compiled verbatim with its own state
 *  (peer0..peer3.c). The transport is a fake in-memory network: LAN datagrams
 *  travel through net_bus.c's sockets, online packets through the GameKit
 *  mock. The scenarios below are the ones no amount of Simulator time can
 *  reproduce on one machine: a party of four forming out of order, a seat that
 *  dies mid-handshake, level transitions, and a player quitting mid-match.
 *
 *  Assertions are about OBSERVABLE agreement between peers -- if the four
 *  disagree on the seat table, the party size, the shared life pool or who is
 *  on screen, that is a desync the device would show as ghost ships.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include "rig_api.h"

#define NPEERS 4

/* --- per-peer entry points (generated by peer.inc) --- */
#define DECL(id) \
	void rig_tick_##id(int ms); \
	void rig_start_online_##id(int mySeat, int numSeats); \
	void rig_init_lan_##id(void); \
	void rig_deliver_gk_##id(int senderSeat, const void* data, int len); \
	void rig_resolve_peer_##id(unsigned int ip); \
	void rig_next_level_##id(void); \
	int  rig_state_##id(void); \
	int  rig_seat_##id(void); \
	int  rig_numseats_##id(void); \
	int  rig_numplayers_##id(void); \
	int  rig_controlled_##id(void); \
	int  rig_lives_##id(void); \
	int  rig_scene_##id(void); \
	int  rig_drawn_##id(int s); \
	int  rig_color_##id(int s); \
	int  rig_ship_##id(int s); \
	void rig_set_loadout_##id(int ship, int color); \
	void rig_set_lives_##id(int n);
DECL(0) DECL(1) DECL(2) DECL(3)

typedef struct peer_api_t {
	void (*tick)(int);
	void (*start_online)(int,int);
	void (*init_lan)(void);
	void (*deliver_gk)(int, const void*, int);
	void (*resolve_peer)(unsigned int);
	void (*next_level)(void);
	int  (*state)(void);
	int  (*seat)(void);
	int  (*numseats)(void);
	int  (*numplayers)(void);
	int  (*controlled)(void);
	int  (*lives)(void);
	int  (*scene)(void);
	int  (*drawn)(int);
	int  (*color)(int);
	int  (*ship)(int);
	void (*set_loadout)(int,int);
	void (*set_lives)(int);
} peer_api_t;

#define API(id) { rig_tick_##id, rig_start_online_##id, rig_init_lan_##id, rig_deliver_gk_##id, \
                  rig_resolve_peer_##id, rig_next_level_##id, rig_state_##id, rig_seat_##id, \
                  rig_numseats_##id, rig_numplayers_##id, rig_controlled_##id, rig_lives_##id, \
                  rig_scene_##id, rig_drawn_##id, rig_color_##id, rig_ship_##id, \
                  rig_set_loadout_##id, rig_set_lives_##id }
static peer_api_t P[NPEERS] = { API(0), API(1), API(2), API(3) };

/* --- rig state --- */
static int gPaused[NPEERS];
static int gAlive[NPEERS];			/* is this peer's device still running? */
static int gMenu[NPEERS];
static int gReloads[NPEERS];
static int gLoads[NPEERS];
static int gOnline = 0;				/* which transport this scenario uses */
static int gSeatOf[NPEERS];			/* online: seat assigned to each peer */
static int gVerbose = 0;

static int gFailures = 0;
static int gChecks = 0;

/* Peer ips: NOT in peer order, so the sorted-IP seat table is a real
   permutation (peer 2 owns the lowest ip and must become seat 0). */
static const unsigned int gIps[NPEERS] = {
	0x0A000014u,	/* 10.0.0.20 -> seat 2 */
	0x0A00001Eu,	/* 10.0.0.30 -> seat 3 */
	0x0A00000Au,	/* 10.0.0.10 -> seat 0 */
	0x0A00000Fu 	/* 10.0.0.15 -> seat 1 */
};
static const int gExpectedSeat[NPEERS] = { 2, 3, 0, 1 };

unsigned int rig_ip_of(int peer) { return gIps[peer]; }
void rig_set_paused(int peer, int p) { gPaused[peer] = p; }
int  rig_is_paused(int peer) { return gPaused[peer]; }
void rig_note_menu(int peer, int menuId) { gMenu[peer] = menuId; }
void rig_note_load(int peer, int sceneId) { gLoads[peer]++; (void)sceneId; }
void rig_note_reload(int peer) { gReloads[peer]++; }
static char gNotice[NPEERS][64];
void rig_note_notice(int peer, const char* text)
{
	strncpy(gNotice[peer], text, sizeof(gNotice[0]) - 1);
	gNotice[peer][sizeof(gNotice[0]) - 1] = 0;
}

void rig_vlog(int peer, const char* fmt, va_list ap)
{
	if (!gVerbose) return;
	printf("      [p%d] ", peer);
	vprintf(fmt, ap);
}

/* GameKit mock: a broadcast to every other LIVE peer, tagged with our seat. */
void rig_gk_send(int peer, const void* data, int len, int reliable)
{
	int i;
	(void)reliable;
	if (!gAlive[peer]) return;
	for (i = 0; i < NPEERS; i++)
	{
		if (i == peer || !gAlive[i]) continue;
		if (gSeatOf[i] < 0) continue;
		P[i].deliver_gk(gSeatOf[peer], data, len);
	}
}

/* --- assertions --- */
static void check(int cond, const char* what, ...)
{
	va_list ap;
	gChecks++;
	if (cond) return;
	gFailures++;
	printf("  FAIL: ");
	va_start(ap, what);
	vprintf(what, ap);
	va_end(ap);
	printf("\n");
}

static void run_frames(int n)
{
	int f, i;
	for (f = 0; f < n; f++)
		for (i = 0; i < NPEERS; i++)
			if (gAlive[i])
				P[i].tick(16);
}

static void reset_rig(int nPeers, int online)
{
	int i;
	rig_bus_reset();
	gOnline = online;
	for (i = 0; i < NPEERS; i++)
	{
		gPaused[i] = 0;
		gAlive[i] = (i < nPeers);
		gMenu[i] = -99;
		gReloads[i] = 0;
		gLoads[i] = 0;
		gSeatOf[i] = -1;
		gNotice[i][0] = 0;
	}
}

#define STATE_RUNNING 3
#define STATE_PRELOAD 2
#define STATE_STARTED 1
#define STATE_UNDET   0

/* ============================ scenarios ============================ */

/* 1. Four devices on a LAN, discovering each other in a scrambled order and
      at different times -- the case a single Mac cannot stage. */
static void scenario_lan_four(void)
{
	int i, j;
	printf("[1] LAN: a party of four forms out of order\n");
	reset_rig(4, 0);

	for (i = 0; i < 4; i++)
	{
		P[i].init_lan();
		P[i].set_loadout(i % 4, 0);	/* everyone picks RED: the dedupe must split them */
	}

	/* Each device registers and browses; discovery trickles in over ~2s in a
	   deliberately ugly order (peer 3 hears about everyone last). */
	run_frames(10);
	P[0].resolve_peer(gIps[2]);
	P[2].resolve_peer(gIps[0]);
	run_frames(30);
	P[1].resolve_peer(gIps[0]);  P[1].resolve_peer(gIps[2]);
	P[0].resolve_peer(gIps[1]);  P[2].resolve_peer(gIps[1]);
	run_frames(40);
	P[3].resolve_peer(gIps[0]);  P[3].resolve_peer(gIps[1]);  P[3].resolve_peer(gIps[2]);
	P[0].resolve_peer(gIps[3]);  P[1].resolve_peer(gIps[3]);  P[2].resolve_peer(gIps[3]);

	/* The settle window (4s) then has to close before anything starts. */
	run_frames(120);
	for (i = 0; i < 4; i++)
		check(P[i].state() != STATE_RUNNING, "peer %d started before the settle window closed", i);

	run_frames(400);

	for (i = 0; i < 4; i++)
	{
		check(P[i].seat() == gExpectedSeat[i], "peer %d seat %d, expected %d (sorted-ip table)",
		      i, P[i].seat(), gExpectedSeat[i]);
		check(P[i].numseats() == 4, "peer %d sees %d seats, expected 4", i, P[i].numseats());
		check(P[i].state() == STATE_RUNNING, "peer %d state %d, expected RUNNING", i, P[i].state());
		check(P[i].numplayers() == 4, "peer %d numPlayers %d, expected 4", i, P[i].numplayers());
		check(P[i].controlled() == gExpectedSeat[i], "peer %d controlledPlayer %d, expected %d",
		      i, P[i].controlled(), gExpectedSeat[i]);
		check(P[i].lives() == 12, "peer %d life pool %d, expected 12 (4 x 3)", i, P[i].lives());
		check(gMenu[i] == -1, "peer %d menu %d, expected MENU_NONE", i, gMenu[i]);
	}

	/* Everyone must agree on the loadout table, and the four colours must be
	   distinct even though all four players picked red. */
	for (i = 0; i < 4; i++)
		for (j = 0; j < 4; j++)
			check(P[i].color(j) == P[0].color(j),
			      "peer %d sees seat %d colour %d, peer 0 sees %d (table disagreement)",
			      i, j, P[i].color(j), P[0].color(j));
	{
		/* Three VISIBLE columns for four seats: the dedupe must spread them
		   over all three and never assign the invisible one (2) unasked --
		   so exactly one colour ends up shared by two seats. */
		int seen[8]; int distinct = 0;
		memset(seen, 0, sizeof(seen));
		for (j = 0; j < 4; j++) seen[P[0].color(j) & 7]++;
		for (j = 0; j < 8; j++) if (seen[j]) distinct++;
		check(distinct == 3, "dedupe produced %d distinct colours for 4 seats, expected 3", distinct);
		check(seen[2] == 0, "the dedupe handed out INVISIBLE bullets unasked");
	}
}

/* 2. A seat vanishes DURING the handshake (app killed while the others wait).
      The barrier must not hang: the party plays on without it. */
static void scenario_lan_drop_in_handshake(void)
{
	int i;
	printf("[2] LAN: a seat dies mid-handshake -- the party must still start\n");
	reset_rig(4, 0);

	for (i = 0; i < 4; i++) { P[i].init_lan(); P[i].set_loadout(i, i); }
	run_frames(10);
	for (i = 0; i < 4; i++)
		for (int k = 0; k < 4; k++)
			if (k != i) P[i].resolve_peer(gIps[k]);

	/* Peer 1 (seat 3) dies BEFORE the settle window closes: it is on everyone's
	   roster but will never send a JOIN. Only the frame-counted handshake
	   watchdog can break this -- the sim clock is paused and the in-match
	   liveness check does not run until the state reaches RUNNING. */
	run_frames(60);
	check(P[2].state() != STATE_RUNNING, "the host started before the settle window closed");
	gAlive[1] = 0;

	run_frames(1500);		/* settle (4s) + NET_SETUP_TIMEOUT_FRAMES (900) + slack */

	for (i = 0; i < 4; i++)
	{
		if (!gAlive[i]) continue;
		check(P[i].state() == STATE_RUNNING, "peer %d state %d after the drop, expected RUNNING", i, P[i].state());
		check(P[i].drawn(3) == 0, "peer %d still draws the seat that never arrived", i);
		check(P[i].drawn(P[i].seat()) == 1, "peer %d parked its OWN ship", i);
		check(P[i].lives() == 9, "peer %d pool %d, expected 9 (3 players present, not 12)",
		      i, P[i].lives());
	}
}

/* 3. Level transition: the whole party must clear the barrier again. */
static void scenario_lan_next_level(void)
{
	int i;
	printf("[3] LAN: the barrier re-arms and the party clears level 2\n");
	reset_rig(4, 0);

	for (i = 0; i < 4; i++) { P[i].init_lan(); P[i].set_loadout(i, i); }
	run_frames(10);
	for (i = 0; i < 4; i++)
		for (int k = 0; k < 4; k++)
			if (k != i) P[i].resolve_peer(gIps[k]);
	run_frames(500);

	for (i = 0; i < 4; i++)
		check(P[i].state() == STATE_RUNNING, "peer %d did not start level 1", i);

	/* Burn a few lives, then everyone finishes the act. */
	for (i = 0; i < 4; i++) P[i].set_lives(7);
	for (i = 0; i < 4; i++) P[i].next_level();

	run_frames(500);

	for (i = 0; i < 4; i++)
	{
		check(P[i].state() == STATE_RUNNING, "peer %d stuck at state %d on level 2", i, P[i].state());
		check(P[i].lives() == 7, "peer %d life pool %d on level 2, expected the carried-over 7",
		      i, P[i].lives());
		check(P[i].scene() == 2, "peer %d scene %d, expected 2", i, P[i].scene());
	}
}

/* 4. A player quits mid-match: his ship parks, everyone else plays on and
      agrees about it. Only the LAST peer leaving ends the session. */
static void scenario_lan_drop_in_match(void)
{
	int i;
	printf("[4] LAN: a player quits mid-match -- the others play on\n");
	reset_rig(4, 0);

	for (i = 0; i < 4; i++) { P[i].init_lan(); P[i].set_loadout(i, i); }
	run_frames(10);
	for (i = 0; i < 4; i++)
		for (int k = 0; k < 4; k++)
			if (k != i) P[i].resolve_peer(gIps[k]);
	run_frames(500);

	gAlive[0] = 0;			/* peer 0 = seat 2 walks out */
	run_frames(700);		/* past NET_PEER_TIMEOUT_MS on the sim clock */

	for (i = 1; i < 4; i++)
	{
		check(P[i].state() == STATE_RUNNING, "peer %d ended the match over one quitter (state %d)",
		      i, P[i].state());
		check(P[i].drawn(2) == 0, "peer %d still draws the quitter's ship (seat 2)", i);
		/* And the survivors were TOLD, on screen -- a ship that just vanishes
		   with no word reads as a bug to the players left behind. */
		check(!strcmp(gNotice[i], "PLAYER 3 LEFT"),
		      "peer %d showed no on-screen notice (got \"%s\")", i, gNotice[i]);
	}

	/* Now the rest leave one by one: the last man standing must fall back to
	   the classic "connection lost" teardown, not sit in a dead match. */
	gAlive[1] = 0;
	run_frames(700);
	gAlive[3] = 0;
	run_frames(700);

	check(P[2].state() != STATE_RUNNING, "the last peer kept running an empty match");
}

/* 5. Online (GameKit): the same party of four, seats handed down by the
      GameKit layer, every packet broadcast to everyone. */
static void scenario_online_four(void)
{
	int i;
	printf("[5] Online: GKMatch party of four\n");
	reset_rig(4, 1);

	for (i = 0; i < NPEERS; i++)
	{
		gSeatOf[i] = gExpectedSeat[i];		/* the sorted-gamePlayerID table */
		P[i].init_lan();					/* same menu entry, transport swapped below */
		P[i].set_loadout(i, 1);				/* everyone picks BLUE */
	}
	for (i = 0; i < NPEERS; i++)
		P[i].start_online(gExpectedSeat[i], 4);

	run_frames(600);

	for (i = 0; i < NPEERS; i++)
	{
		check(P[i].state() == STATE_RUNNING, "online peer %d state %d, expected RUNNING", i, P[i].state());
		check(P[i].numplayers() == 4, "online peer %d numPlayers %d", i, P[i].numplayers());
		check(P[i].lives() == 12, "online peer %d pool %d, expected 12", i, P[i].lives());
		check(P[i].controlled() == gExpectedSeat[i], "online peer %d controlledPlayer wrong", i);
	}
	for (i = 0; i < NPEERS; i++)
	{
		int j;
		for (j = 0; j < 4; j++)
			check(P[i].color(j) == P[2].color(j), "online peer %d disagrees on seat %d colour", i, j);
	}
}

/* 6. Two players only, the tester's regression path: the seat model must
      behave exactly like the old boolean roles. */
static void scenario_lan_two(void)
{
	int i;
	printf("[6] LAN: the classic pair (regression)\n");
	reset_rig(2, 0);

	for (i = 0; i < 2; i++) { P[i].init_lan(); P[i].set_loadout(0, 0); }
	run_frames(10);
	P[0].resolve_peer(gIps[1]);
	P[1].resolve_peer(gIps[0]);
	run_frames(500);

	/* ips: peer0 = .20, peer1 = .30 -> peer 0 is the lower ip = seat 0 = host */
	check(P[0].seat() == 0, "peer 0 (lower ip) seat %d, expected 0/host", P[0].seat());
	check(P[1].seat() == 1, "peer 1 seat %d, expected 1", P[1].seat());
	for (i = 0; i < 2; i++)
	{
		check(P[i].state() == STATE_RUNNING, "pair peer %d state %d", i, P[i].state());
		check(P[i].numplayers() == 2, "pair peer %d numPlayers %d, expected 2", i, P[i].numplayers());
		check(P[i].lives() == 6, "pair peer %d pool %d, expected 6 (2 x 3)", i, P[i].lives());
	}
	/* Both picked red: exactly the old "player two shifts" rule. */
	check(P[0].color(0) == 0 && P[0].color(1) == 1,
	      "pair colours (%d,%d), expected (0,1) -- the 2010 shift rule",
	      P[0].color(0), P[0].color(1));
	check(P[1].color(0) == P[0].color(0) && P[1].color(1) == P[0].color(1),
	      "the pair disagrees on the colour table");
}

/* 7. The review's Failure A/B: device B never hears about device C from
      Bonjour at all. Without roster gossip B seats the party differently (or
      identically-numbered but shorter), and the four devices run different
      simulations -- or every packet fails its identity check and nobody ever
      starts. The gossip in the lobby adverts has to close this. */
static void scenario_lan_partial_discovery(void)
{
	int i;
	printf("[7] LAN: one device never discovers another -- gossip must repair it\n");
	reset_rig(4, 0);

	for (i = 0; i < 4; i++) { P[i].init_lan(); P[i].set_loadout(i, 0); }
	run_frames(10);

	/* Peer 2 (the lowest ip = the host) sees everyone. */
	P[2].resolve_peer(gIps[0]); P[2].resolve_peer(gIps[1]); P[2].resolve_peer(gIps[3]);
	/* Peer 0 only ever hears the host. */
	P[0].resolve_peer(gIps[2]);
	/* Peer 3 hears the host and peer 0. */
	P[3].resolve_peer(gIps[2]); P[3].resolve_peer(gIps[0]);
	/* Peer 1 hears NOBODY but the host -- and nobody but the host hears it
	   directly. Everything else must arrive by gossip. */
	P[1].resolve_peer(gIps[2]);

	run_frames(900);

	for (i = 0; i < 4; i++)
	{
		check(P[i].numseats() == 4, "peer %d sees %d seats after gossip, expected 4", i, P[i].numseats());
		check(P[i].seat() == gExpectedSeat[i], "peer %d seat %d after gossip, expected %d",
		      i, P[i].seat(), gExpectedSeat[i]);
		check(P[i].state() == STATE_RUNNING, "peer %d state %d after gossip, expected RUNNING", i, P[i].state());
		check(P[i].numplayers() == 4, "peer %d numPlayers %d after gossip", i, P[i].numplayers());
		check(P[i].lives() == 12, "peer %d pool %d after gossip, expected 12", i, P[i].lives());
	}
	/* Nobody may be handed the invisible-bullet handicap: with four seats and
	   only three VISIBLE columns, the dedupe shares a colour instead. */
	for (i = 0; i < 4; i++)
		check(P[0].color(i) != 2,
		      "seat %d was silently given INVISIBLE bullets by the dedupe", i);
}

/* 8. Three players: an odd party size, which the formation, the pool and the
      barrier all have to handle without a fourth to lean on. */
static void scenario_lan_three(void)
{
	int i, k;
	printf("[8] LAN: a party of three\n");
	reset_rig(3, 0);

	for (i = 0; i < 3; i++) { P[i].init_lan(); P[i].set_loadout(i, i); }
	run_frames(10);
	for (i = 0; i < 3; i++)
		for (k = 0; k < 3; k++)
			if (k != i) P[i].resolve_peer(gIps[k]);
	run_frames(500);

	/* ips .20/.30/.10 -> peer 2 is seat 0 (host), peer 0 seat 1, peer 1 seat 2 */
	check(P[2].seat() == 0, "three-party host seat %d, expected 0", P[2].seat());
	for (i = 0; i < 3; i++)
	{
		check(P[i].numseats() == 3, "peer %d sees %d seats, expected 3", i, P[i].numseats());
		check(P[i].state() == STATE_RUNNING, "peer %d state %d, expected RUNNING", i, P[i].state());
		check(P[i].numplayers() == 3, "peer %d numPlayers %d, expected 3", i, P[i].numplayers());
		check(P[i].lives() == 9, "peer %d pool %d, expected 9 (3 x 3)", i, P[i].lives());
	}
}

/* 9. Online, mid-match drop: only the HOST's clock decides, and its activeMask
      is what tells the others. Without that adoption the clients keep a ghost
      ship (and mirror its life counter) for a player who is gone. */
static void scenario_online_drop(void)
{
	int i;
	printf("[9] Online: a mid-match drop travels by the host's activeMask\n");
	reset_rig(4, 1);

	for (i = 0; i < NPEERS; i++)
	{
		gSeatOf[i] = gExpectedSeat[i];
		P[i].init_lan();
		P[i].set_loadout(i, i);
	}
	for (i = 0; i < NPEERS; i++)
		P[i].start_online(gExpectedSeat[i], 4);
	run_frames(600);
	for (i = 0; i < NPEERS; i++)
		check(P[i].state() == STATE_RUNNING, "online peer %d never started", i);

	gAlive[1] = 0;			/* seat 3 loses its connection */
	run_frames(700);

	for (i = 0; i < NPEERS; i++)
	{
		if (!gAlive[i]) continue;
		check(P[i].drawn(3) == 0, "online peer %d still draws the departed seat 3", i);
		check(P[i].state() == STATE_RUNNING, "online peer %d ended the match over one drop", i);
	}
}

int main(int argc, char** argv)
{
	if (argc > 1 && !strcmp(argv[1], "-v")) gVerbose = 1;

	printf("=== net_rig: four peers, one process, the real netchannel.c ===\n");

	scenario_lan_two();
	scenario_lan_four();
	scenario_lan_drop_in_handshake();
	scenario_lan_next_level();
	scenario_lan_drop_in_match();
	scenario_online_four();
	scenario_lan_partial_discovery();
	scenario_lan_three();
	scenario_online_drop();

	printf("=== %d checks, %d failures ===\n", gChecks, gFailures);
	return gFailures ? 1 : 0;
}
